version: '3'
services:
  postgres:
    image: postgres:alpine
    ports:
    - 5432:5432
  mongo:
    image: mongo
    ports:
    - 27017:27017
  opentsdb:
    image: petergrace/opentsdb-docker
    ports:
    - 4242:4242
  neo4j:
    image: neo4j
    ports: 
    - 7474:7474
    - 7687:7687
    environment:
    - NEO4J_AUTH=none
